// <auto-generated />
namespace Proyecto01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migracion2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migracion2));
        
        string IMigrationMetadata.Id
        {
            get { return "202412070318104_migracion2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
